### ISSUE TITLE
Cambiar url environments[real] y hacer un nuevo tag?

### ISSUE THREAD

**Issue by hi-rafa** [eusonlito/Ceca-TPV#6]
Hola @eusonlito ,
Veo que has añadido correctamente la nueva URL de entorno test en la clase TPV, sin emabrgo no veo que haya nigun nuevo tag con los cambios.

    private $environments = array(
        'test' => 'https://tpv.ceca.es/tpvweb/tpv/compra.action',
        'real' => 'https://pgw.ceca.es/cgi-bin/tpv'
    );

Tag 1.2
https://github.com/eusonlito/Ceca-TPV/blob/v1.2.0/src/Ceca/Tpv/Tpv.php

Master
https://github.com/eusonlito/Ceca-TPV/blob/master/src/Ceca/Tpv/Tpv.php

**Comprobando la documentación de ceca creo que habría que cambiar la URL del entorno real.**

[https://comercios.ceca.es/docs_constpv/img/manual_comercios.pdf](https://comercios.ceca.es/docs_constpv/img/manual_comercios.pdf)

El TPV de Cecabank consta de dos entornos en funcionamiento, Uno para pruebas y otro para
producción. A continuación mostramos sus direcciones:
https://tpv.ceca.es/tpvweb/tpv/compra.action ENTORNO DE DESARROLLO
https://pgw.ceca.es/tpvweb/tpv/compra.action ENTORNO DE PRODUCCIÓN
Estos serán los únicos valores válidos en el campo ACTION de los formularios descritos 

    private $environments = array(
        'test' => 'https://tpv.ceca.es/tpvweb/tpv/compra.action',
        'real' => 'https://pgw.ceca.es/tpvweb/tpv/compra.action'
    );

**Comment by eusonlito** [comment]
Listo, gracias! https://github.com/eusonlito/Ceca-TPV/releases
